development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mouni_develpment
  pool: 5
  username: root
  password: root
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mouni_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mouni_production
  pool: 5
  username: root
  password: root
